### ISSUE TITLE
AttributeError: 'module' object has no attribute 'EmbedID'

### ISSUE THREAD

**Issue by hedgy123** [orenmel/context2vec#12]
Hi,
  I am trying to train a model on my corpus.  So I did:

    python context2vec/train/corpus_by_sent_length.py my_file

 which went fine, and then:

    python context2vec/train/train_context2vec.py -i my_file.DIR -c lstm --deep yes -t 3 --dropout 0.0 -u 300 -e 10 -p 0.75 -b 100 -g -1

  (I don't have a GPU-enabled machine).  Here's what I get:

GPU: -1
Minibatch-size: 100
Context type: lstm
Deep: True
Dropout: 0.0
Trimfreq: 3
NS Power: 0.75

n_vocab: 62690
corpus size: 95350988
Traceback (most recent call last):
  File "context2vec/train/train_context2vec.py", line 114, in <module>
    model = BiLstmContext(args.deep, args.gpu, reader.word2index, context_word_units, lstm_hidden_units, target_word_units, loss_func, True, args.dropout)
  File "/USER_DIR_NOT_SHOWN/anaconda2/envs/py27base/lib/python2.7/site-packages/context2vec/common/context_models.py", line 76, in __init__
    l2r_embedding=F.EmbedID(n_vocab, in_units)
AttributeError: 'module' object has no attribute 'EmbedID'

   Could you please help me understand how to make it work correctly?  Thank you!

**Comment by orenmel** [comment]
Hi. This looks like a Chainer version compatibility issue. Which version of Chainer are you using? If it's not Chainer 1.7 then try switching to that version.

**Comment by 14chanwa** [comment]
Hi, I had the same issue ; actually I couldn't install Chainer 1.7 (some cython issues). A hotfix is to change
        l2r_embedding=F.EmbedID(n_vocab, in_units)
        r2l_embedding=F.EmbedID(n_vocab, in_units)
to 
        l2r_embedding=L.EmbedID(n_vocab, in_units)
        r2l_embedding=L.EmbedID(n_vocab, in_units)
(looks like these functions changed package since then)
